spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/travelDiary
    username: sa
    passwored:
    driver-class-name: org.h2.Driver
  messages:
    basename: errors
#  sevlet:
#    multipart:
#      max-file-size: 1MB
#      max-request-size: 10MB

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show-sql: true
#        format-sql: true

logging:
  level:
    org.hibernate.SQL: debug

#decorator:
#  datasource:
#    p6spy:
#      enable-logging: true

file:
  dir: C:\Users\ogd00\Desktop\공부\프로젝트\travelDiaryBox\images/
