spring:
  messages:
    basename: errors

  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB

  profiles:
    active: prod
#    default: prod
#    include: oauth

logging:
  level:
    org.hibernate.SQL: debug

#decorator:
#  datasource:
#    p6spy:
#      enable-logging: true

server:
  servlet:
    session:
      tracking-modes: cookie
