spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/travelDiary
    username: sa
    passwored:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
#        show-sql: true
        format-sql: true

logging:
  level:
    org.hibernate.SQL: debug