spring:
  datasource:
    url: jdbc:mysql://localhost:3306/travel?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: travel1!
    driver-class-name: com.mysql.cj.jdbc.Driver

  messages:
    basename: errors

  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB

  profiles:
    include: oauth

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
#        show_sql: true
        format_sql: true

#  session:
#    store-type: jdbc

logging:
  level:
    org.hibernate.SQL: debug

decorator:
  datasource:
    p6spy:
      enable-logging: true

file:
  dir: C:\Users\ogd00\Desktop\공부\프로젝트\travelDiaryBox\images/

server:
  servlet:
    session:
      tracking-modes: cookie