spring:
  messages:
    basename: errors

  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB

  profiles:
    include: oauth,real-db

logging:
  level:
    org.hibernate.SQL: debug

file:
  dir: C:\Users\ogd00\Desktop\공부\프로젝트\travelDiaryBox\images/

server:
  servlet:
    session:
      tracking-modes: cookie