spring:
  profiles:
    group:
      prod:
        prod-db,
        aws

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        #        show_sql: true
        format_sql: false

file:
  dir: